<a href="https://colab.research.google.com/github/Mpumelelogqweta/TesnsorFlow-Python-Neural-Networks/blob/main/Myproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# CREATING TENSORS



---



In [ ]:
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(32, tf.int16)
floating = tf.Variable(3.567, tf.float64)

# RANK/DEGREE OF TENSORS 



---



```
#These terms simply mean the number of dimensions involved in the tensor.


---


```



In [ ]:
rank1_tensor = tf.Variable(["Test", "run", "code"], tf.string)
rank2_tensor = tf.Variable([["Test", "Ok"],["Test", "Yes"]], tf.string)

**To determine the rank of a tensor we can call the following method.**

In [ ]:

tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# SHAPE OF TENSORS



---


```
To get the shape of a tensor we use the shape attribute.


---


```







In [ ]:
rank1_tensor.shape

TensorShape([3])

# CHANGING SHAPE

---



```
The number of elements of a tensor is the product  of the sizes of all its shapes.
There are often many shapes that have the same same number of elements, 
making it convinient to be able change the shape of a tensor. 

---


```



In [ ]:
tensor1 = tf.ones([1,2,3])         #tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  #reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3,-1])   #-1 tells the tensor to calculate the size of the dimension in that place 
                                        #this will reshape the tensor to [3,2]
                                      
#The number of elements in the reshaped tensor Must match the number in the original

In [ ]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


 Types of Tensor
 
 ---








```
*   Variable 
*   Constant
*   Placeholder
*   SparseTensor

Note: With the exception of Variable all of these tensors are immutable, meaning their value may not change during execution

---


```



# EVALUATING TENSORS

---



In [ ]:
with tf.Session() as sess: #creates  a session using the default graph
  tensor.eval()       # tensor will of course be the name of your tensor